version: "3.1"
services:
  resource-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: pg-username-resource
      POSTGRES_PASSWORD: pg-password-resource
      POSTGRES_DB: pg-db-resource
    volumes:
      - ./data/resource-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
  auth-db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: pg-username-auth
      POSTGRES_PASSWORD: pg-password-auth
      POSTGRES_DB: pg-db-auth
    volumes:
      - ./data/auth-db:/var/lib/postgresql/data
    ports:
      - 5433:5432
  kv-store:
    image: redis:4.0.5-alpine
    command:
      ["redis-server", "--appendonly", "yes", "--requirepass", "redis-password"]
    hostname: redis
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
